# Generated by Django 5.2.11 on 2026-02-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='academics.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfee'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_structure')},
        ),
    ]
